// Mocks generated by Mockito 5.0.17 from annotations
// in tribe_app/test/futures/post/infrastrucure/repository/post_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tribe_app/core/network/network_info.dart' as _i2;
import 'package:tribe_app/futures/post/domain/entities/post.dart' as _i5;
import 'package:tribe_app/futures/post/infrastructure/data/post_remot_data.dart'
    as _i4;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [NetWorkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetWorkInfo extends _i1.Mock implements _i2.NetWorkInfo {
  MockNetWorkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
}

/// A class which mocks [PostRemoteData].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostRemoteData extends _i1.Mock implements _i4.PostRemoteData {
  MockPostRemoteData() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i5.Post>> getPosts() =>
      (super.noSuchMethod(Invocation.method(#getPosts, []),
              returnValue: Future<List<_i5.Post>>.value(<_i5.Post>[]))
          as _i3.Future<List<_i5.Post>>);
}
